name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - staging
      - production

jobs:
  # Job untuk Development
  build-development:
    name: Build and Deploy Development
    runs-on: ubuntu-latest
    if: github.ref_name == 'development'
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # https://github.com/marketplace/actions/webfactory-ssh-agent
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Build and Deploy to Development Droplet
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.DROPLET_IP }} << 'EOF'
            set -e
            cd ${{ secrets.PATH_APP }}
            git pull origin development
            make build-development
            make start-development
          EOF

  # Job untuk Staging
  build-staging:
    name: Build and Deploy Staging
    runs-on: ubuntu-latest
    needs: build-development
    if: github.ref_name == 'staging'
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # https://github.com/marketplace/actions/webfactory-ssh-agent
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Build and Deploy to Staging Droplet
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.DROPLET_IP }} << 'EOF'
            set -e
            cd ${{ secrets.PATH_APP }}
            git pull origin staging
            make build-staging
            make start-staging
          EOF

  # Job untuk Production
  build-production:
    name: Build and Deploy Production
    runs-on: ubuntu-latest
    needs: build-staging
    if: github.ref_name == 'production'
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # https://github.com/marketplace/actions/webfactory-ssh-agent
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Build and Deploy to Production Droplet
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.DROPLET_IP }} << 'EOF'
            set -e
            cd ${{ secrets.PATH_APP }}
            git pull origin production
            make build-production
            make start-production
          EOF
